#! /bin/bash
#
# Copyright (c) 2022 Riverbed Technology LLC
#
# This software is licensed under the terms and conditions of the MIT License
# accompanying the software ("License").  This software is distributed "AS IS"
# as set forth in the License.
#

run_rsync()
{
	export PATH="$PATH:$MSYSRSYNCPATH\\lib"
	"$MSYSRSYNCPATH\\bin\\rsync" "$@"
}

get_rsync_for_windows && run_rsync "$@"
